/*
 * exercise4.c
 *
 *  Created on: Sep 13, 2024
 *      Author: USER
 */

#include "exercise4.h"
int count = 0;
void display7SEG(int num) {
	switch (num) {
	case 0:
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, RESET);
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, RESET);
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, RESET);
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, RESET);
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, RESET);
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_13, RESET);
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_14, SET);
		break;
	case 1:
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, SET);
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, RESET);
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, RESET);
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, SET);
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, SET);
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_13, SET);
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_14, SET);

		break;
	case 2:
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, RESET); //0
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, RESET); //1
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, SET); //2
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, RESET); //3
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, RESET); //4
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_13, SET); //5
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_14, RESET); //6
		break;
	case 3:
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, RESET); //0
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, RESET); //1
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, RESET); //2
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, RESET); //3
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, SET); //4
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_13, SET); //5
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_14, RESET); //6
		break;
	case 4:
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, SET); //0
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, RESET); //1
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, RESET); //2
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, SET); //3
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, SET); //4
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_13, RESET); //5
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_14, RESET); //6
		break;
	case 5:
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, RESET); //0
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, SET); //1
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, RESET); //2
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, RESET); //3
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, SET); //4
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_13, RESET); //5
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_14, RESET); //6
		break;
	case 6:
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, RESET); //0
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, SET); //1
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, RESET); //2
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, RESET); //3
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, RESET); //4
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_13, RESET); //5
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_14, RESET); //6
		break;
	case 7:
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, RESET); //0
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, RESET); //1
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, RESET); //2
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, SET); //3
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, SET); //4
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_13, SET); //5
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_14, SET); //6
		break;
	case 8:
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, RESET); //0
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, RESET); //1
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, RESET); //2
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, RESET); //3
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, RESET); //4
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_13, RESET); //5
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_14, RESET); //6
		break;
	case 9:
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, RESET); //0
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, RESET); //1
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, RESET); //2
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, RESET); //3
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, SET); //4
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_13, RESET); //5
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_14, RESET); //6

		break;
	}
}
;

void init_exercise4() {
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, RESET);
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, RESET);
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, RESET);
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, RESET);
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, RESET);
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_13, RESET);
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_14, RESET);
}
void exercise4_run(){
	if (count >= 10) {
				count = 0;
			}
			display7SEG(count++);
}
