/*
 * exercise7.c
 *
 *  Created on: Sep 13, 2024
 *      Author: USER
 */

#include"exercise7.h"
void clearAllClock() {
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, RESET); //L1
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, RESET); //L2
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_6, RESET); //L3
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, RESET); //L4
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, RESET); //L5
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, RESET); //L6
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, RESET); //L7
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, RESET); //L8
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, RESET); //L9
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_13, RESET); //10
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_14, RESET); //11
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_15, RESET); //12
}
void init_exercise7() {
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, SET); //L1
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, SET); //L2
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_6, SET); //L3
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, SET); //L4
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, SET); //L5
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, SET); //L6
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, SET); //L7
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, SET); //L8
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, SET); //L9
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_13, SET); //10
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_14, SET); //11
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_15, SET); //12
}
void exercise7_run() {
	clearAllClock();
}
